### ISSUE TITLE
Il manque le fetch-config.dart ou un example pour le créer nous-même :)

### ISSUE THREAD

**Issue by Grrravity** [jcammas/Lunii_movie#1]
Peux-tu commiter en fetch-config.dart avec des placeholders pour qu'on puisse y mettre nos clés api et tout ce dont ton app à besoin
Merci :)

**Comment by jcammas** [comment]
Bonjour, oui je l'ai transmis à Rodolphe par mail, je ne savais pas si je pouvais push la clé, je l'envoie de suite pas de souci

**Comment by Grrravity** [comment]
En effet t'embête pas il est dans le mail 🤦🏼

**Comment by Grrravity** [comment]
Pas besoin ne t'embête pas
Mais un petit fetch-config.dart.example aurait pu être utile dans lib/config/ ça aiderai pour tes futurs associés sur cette magnifique app :P

**Comment by jcammas** [comment]
En effet ! Bonne idée, j'y penserai à l'avenir :)

**Comment by Grrravity** [comment]
pssst 🥷 💨 
il manque un b à omdbapi.com dans le fetch-config.dart

🤣 
Merci en tout cas ! beau useEffect - debounce ;)

**Comment by jcammas** [comment]
aha oui je voulais push le bon du coup quand tu m'as demandé je m'en suis rendu compte, j'ai eu l'erreur à un moment effectivement, merci :)
